ktor:
  application:
    modules:
      - com.seumelhorcaminho.ApplicationKt.module
  deployment:
    port: 8080

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: ${JDBC_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
